// <auto-generated />
using System;
using AppTesisAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppTesisAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814063922_AddAppointmentLifecycle")]
    partial class AddAppointmentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppTesisAPI.Models.AuditoriaAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaAccesos");
                });

            modelBuilder.Entity("AppTesisAPI.Models.AuditoriaEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidad", "EntidadId");

                    b.HasIndex("FechaUtc", "Accion");

                    b.ToTable("AuditoriaEventos");
                });

            modelBuilder.Entity("AppTesisAPI.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EstadoActualizadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaAtencionUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaEstadoUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PsicologoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoActualizadoPorUsuarioId");

                    b.HasIndex("PsicologoId", "Fecha");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("AppTesisAPI.Models.CitaHistorialEstado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CambiadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CambiadoPorUsuarioId");

                    b.HasIndex("CitaId", "FechaUtc");

                    b.ToTable("CitaHistorialEstados");
                });

            modelBuilder.Entity("AppTesisAPI.Models.ConsentimientoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAceptacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("VersionDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaAceptacion");

                    b.ToTable("ConsentimientosUsuario");
                });

            modelBuilder.Entity("AppTesisAPI.Models.Credenciales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Credenciales");
                });

            modelBuilder.Entity("AppTesisAPI.Models.DocumentoProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotivoRechazo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilPsicologoId")
                        .HasColumnType("integer");

                    b.Property<int?>("RevisadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HashSha256");

                    b.HasIndex("PerfilPsicologoId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("PerfilPsicologoId", "Estado");

                    b.ToTable("DocumentosProfesionales");
                });

            modelBuilder.Entity("AppTesisAPI.Models.HistorialPredictivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("HistorialPredictivo");
                });

            modelBuilder.Entity("AppTesisAPI.Models.NotaSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("PlanAccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PsicologoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("PacienteId", "PsicologoId", "Fecha");

                    b.ToTable("NotasSeguimiento");
                });

            modelBuilder.Entity("AppTesisAPI.Models.PacientePsicologo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("PsicologoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "PsicologoId")
                        .IsUnique();

                    b.ToTable("PacientePsicologos");
                });

            modelBuilder.Entity("AppTesisAPI.Models.PerfilPsicologo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AniosExperiencia")
                        .HasColumnType("integer");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoVerificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoStorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoVerificacion");

                    b.HasIndex("NumeroCedula")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilesPsicologo");
                });

            modelBuilder.Entity("AppTesisAPI.Models.Psicologo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Psicologos");
                });

            modelBuilder.Entity("AppTesisAPI.Models.RecuperacionPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("RecuperacionPasswords");
                });

            modelBuilder.Entity("AppTesisAPI.Models.RegistrosEmocionales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NivelAnimo")
                        .HasColumnType("integer");

                    b.Property<int>("NivelEstres")
                        .HasColumnType("integer");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("RegistrosEmocionales");
                });

            modelBuilder.Entity("AppTesisAPI.Models.SeguimientoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Respuesta1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Respuesta2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Respuesta3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TareasCompletadas")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTareas")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique();

                    b.ToTable("SeguimientosUsuario");
                });

            modelBuilder.Entity("AppTesisAPI.Models.TestEstresLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("P1")
                        .HasColumnType("integer");

                    b.Property<int>("P10")
                        .HasColumnType("integer");

                    b.Property<int>("P11")
                        .HasColumnType("integer");

                    b.Property<int>("P12")
                        .HasColumnType("integer");

                    b.Property<int>("P2")
                        .HasColumnType("integer");

                    b.Property<int>("P3")
                        .HasColumnType("integer");

                    b.Property<int>("P4")
                        .HasColumnType("integer");

                    b.Property<int>("P5")
                        .HasColumnType("integer");

                    b.Property<int>("P6")
                        .HasColumnType("integer");

                    b.Property<int>("P7")
                        .HasColumnType("integer");

                    b.Property<int>("P8")
                        .HasColumnType("integer");

                    b.Property<int>("P9")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("TestEstresLaboral");
                });

            modelBuilder.Entity("AppTesisAPI.Models.TestPHQ9", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("P1")
                        .HasColumnType("integer");

                    b.Property<int>("P2")
                        .HasColumnType("integer");

                    b.Property<int>("P3")
                        .HasColumnType("integer");

                    b.Property<int>("P4")
                        .HasColumnType("integer");

                    b.Property<int>("P5")
                        .HasColumnType("integer");

                    b.Property<int>("P6")
                        .HasColumnType("integer");

                    b.Property<int>("P7")
                        .HasColumnType("integer");

                    b.Property<int>("P8")
                        .HasColumnType("integer");

                    b.Property<int>("P9")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("TestPHQ9");
                });

            modelBuilder.Entity("AppTesisAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppTesisAPI.Models.VerificacionProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentoProfesionalId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilPsicologoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("DocumentoProfesionalId");

                    b.HasIndex("PerfilPsicologoId", "FechaUtc");

                    b.ToTable("VerificacionesProfesionales");
                });

            modelBuilder.Entity("AppTesisAPI.Models.AuditoriaEvento", b =>
                {
                    b.HasOne("AppTesisAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AppTesisAPI.Models.Cita", b =>
                {
                    b.HasOne("AppTesisAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EstadoActualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AppTesisAPI.Models.CitaHistorialEstado", b =>
                {
                    b.HasOne("AppTesisAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CambiadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppTesisAPI.Models.Cita", null)
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppTesisAPI.Models.DocumentoProfesional", b =>
                {
                    b.HasOne("AppTesisAPI.Models.PerfilPsicologo", null)
                        .WithMany()
                        .HasForeignKey("PerfilPsicologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTesisAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AppTesisAPI.Models.NotaSeguimiento", b =>
                {
                    b.HasOne("AppTesisAPI.Models.Cita", null)
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AppTesisAPI.Models.PerfilPsicologo", b =>
                {
                    b.HasOne("AppTesisAPI.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("AppTesisAPI.Models.PerfilPsicologo", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppTesisAPI.Models.VerificacionProfesional", b =>
                {
                    b.HasOne("AppTesisAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppTesisAPI.Models.DocumentoProfesional", null)
                        .WithMany()
                        .HasForeignKey("DocumentoProfesionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppTesisAPI.Models.PerfilPsicologo", null)
                        .WithMany()
                        .HasForeignKey("PerfilPsicologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
